openapi: 3.0.0
info:
  title: gas-price-api-docs
  version: '1.0'
  contact:
    name: John Guo
    email: gjuoun@gmail.com
servers:
  - url: 'http://localhost:6002'
paths:
  /all:
    get:
      summary: GET all stations
      tags: []
      responses:
        '200':
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              examples:
                example:
                  value:
                    success: true
                    data:
                      - station_brand: Wilsons
                        station_address: '30 Farnham Gate Rd & Dunbrack St'
                        station_id: 72164
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 72164
                            prices:
                              - isCash: true
                                price: 71.8
                                reportedBy: Brucevanf
                                postedTime: '2020-05-12T11:18:55.173Z'
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 72164
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 72164
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                      - station_brand: Wilsons
                        station_address: '289 Herring Cove Rd & Bradford St'
                        station_id: 12198
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 73.3
                                reportedBy: Brucevanf
                                postedTime: '2020-05-12T11:18:55.032Z'
                              - isCash: false
                                price: 0
                          - id: 2
                            fuelType: Midgrade
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                      - station_brand: Petro-Canada
                        station_address: '6389 Quinpool Rd & Oxford Street'
                        station_id: 189618
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 189618
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T14:46:43.844Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 189618
                            prices:
                              - isCash: false
                                price: 81.2
                                reportedBy: GodPY
                                postedTime: '2020-05-11T18:32:02.887Z'
                          - id: 3
                            fuelType: Premium
                            stationId: 189618
                            prices:
                              - isCash: false
                                price: 84.7
                                reportedBy: GodPY
                                postedTime: '2020-05-11T18:32:02.903Z'
                      - station_brand: Irving
                        station_address: '6515 Quinpool Rd & Elm St'
                        station_id: 24141
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 24141
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T14:46:42.230Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 24141
                            prices:
                              - isCash: false
                                price: 81.2
                                reportedBy: GodPY
                                postedTime: '2020-05-11T18:32:17.086Z'
                          - id: 3
                            fuelType: Premium
                            stationId: 24141
                            prices:
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 24141
                            prices:
                              - isCash: false
                                price: 0
                      - station_brand: Petro-Canada
                        station_address: 7015 Bayers Rd near Ralston Ave
                        station_id: 8900
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 8900
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T13:47:23.213Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 8900
                            prices:
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 8900
                            prices:
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 8900
                            prices:
                              - isCash: false
                                price: 0
                      - station_brand: Canadian Tire
                        station_address: '6590 Bayers Rd & Connaught Ave'
                        station_id: 189619
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 189619
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T13:46:05.470Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 189619
                            prices:
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 189619
                            prices:
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 189619
                            prices:
                              - isCash: false
                                price: 0
                      - station_brand: Esso
                        station_address: '6020 Young St & Robie St'
                        station_id: 1704
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 1704
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T13:42:37.780Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 1704
                            prices:
                              - isCash: false
                                price: 81.2
                                reportedBy: GodPY
                                postedTime: '2020-05-11T18:32:29.820Z'
                          - id: 3
                            fuelType: Premium
                            stationId: 1704
                            prices:
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 1704
                            prices:
                              - isCash: false
                                price: 0
                      - station_brand: Ultramar
                        station_address: '2816 Gottingen St   & Almon St'
                        station_id: 12197
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 12197
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T13:40:59.902Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 12197
                            prices:
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 12197
                            prices:
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 12197
                            prices:
                              - isCash: false
                                price: 0
                      - station_brand: Shell
                        station_address: '2616 Robie St & North St'
                        station_id: 12192
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 12192
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T13:34:28.837Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 12192
                            prices:
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 12192
                            prices:
                              - isCash: false
                                price: 0
                      - station_brand: Esso
                        station_address: '7151 Chebucto Rd & Clinton Ave'
                        station_id: 1910
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 1910
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: KingKaung
                                postedTime: '2020-05-12T13:30:58.211Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 1910
                            prices:
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 1910
                            prices:
                              - isCash: false
                                price: 0
      operationId: get-all
  /cheap:
    get:
      summary: GET gas price ranking
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              examples:
                example:
                  value:
                    success: true
                    data:
                      - station_brand: Wilsons
                        station_address: '30 Farnham Gate Rd & Dunbrack St'
                        station_id: 72164
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 72164
                            prices:
                              - isCash: true
                                price: 71.8
                                reportedBy: Brucevanf
                                postedTime: '2020-05-12T11:18:55.173Z'
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 72164
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 72164
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                      - station_brand: Wilsons
                        station_address: '289 Herring Cove Rd & Bradford St'
                        station_id: 12198
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 73.3
                                reportedBy: Brucevanf
                                postedTime: '2020-05-12T11:18:55.032Z'
                              - isCash: false
                                price: 0
                          - id: 2
                            fuelType: Midgrade
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                          - id: 3
                            fuelType: Premium
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                          - id: 4
                            fuelType: Diesel
                            stationId: 12198
                            prices:
                              - isCash: true
                                price: 0
                              - isCash: false
                                price: 0
                      - station_brand: Petro-Canada
                        station_address: '6389 Quinpool Rd & Oxford Street'
                        station_id: 189618
                        fuels:
                          - id: 1
                            fuelType: Regular
                            stationId: 189618
                            prices:
                              - isCash: false
                                price: 76.8
                                reportedBy: Abhijithvikram
                                postedTime: '2020-05-12T17:24:46.981Z'
                          - id: 2
                            fuelType: Midgrade
                            stationId: 189618
                            prices:
                              - isCash: false
                                price: 81.2
                                reportedBy: GodPY
                                postedTime: '2020-05-11T18:32:02.887Z'
                          - id: 3
                            fuelType: Premium
                            stationId: 189618
                            prices:
                              - isCash: false
                                price: 84.7
                                reportedBy: GodPY
                                postedTime: '2020-05-11T18:32:02.903Z'
        '400':
          description: 'Bad Request, top is not number'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              examples:
                example:
                  value:
                    success: false
                    message: 'Missing query parameter - top:number '
      operationId: get-cheap
      parameters:
        - schema:
            type: number
          in: query
          name: top
          required: true
    parameters: []
components:
  schemas:
    ApiResponse:
      title: ApiResponse
      type: object
      description: 'if success is true, return data, else return message'
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/Station'
        message:
          type: string
      required:
        - success
    Station:
      title: Station
      type: object
      properties:
        station_brand:
          type: string
        station_address:
          type: string
        station_id:
          type: number
        fuels:
          type: array
          items:
            $ref: '#/components/schemas/Fuel'
    Fuel:
      title: Fuel
      type: object
      properties:
        id:
          type: number
        fuelType:
          type: string
          description: '"Regular" | "Midgrade" | "Premium" | "Diesel"'
        prices:
          type: array
          items:
            $ref: '#/components/schemas/PumpPrice'
      required:
        - id
        - fuelType
        - prices
    PumpPrice:
      title: PumpPrice
      type: object
      properties:
        isCash:
          type: boolean
        price:
          type: number
        reportedBy:
          type: string
        postedTime:
          type: string
      required:
        - isCash
        - price
